### PR TITLE
Fix: grid flow set deselect allowed to false

### LINKED ISSUE #850: Grid: setDeselectAllowed (false) not usable because of an exception
Version: 14.1.2 (observed just after upgrade) 
Description: If we define a grid, one of the simplest and largely used sequence of operations raise an exception:   
- set grid with deselected allowed false (relatively new vaadin feature)
- grid: set items 
- grid: select first item 
- grid: set items (again)
The exception is not raised for deselected allowed false or if we do not select any grid row.

In all our modules (many). now we have bugs in all the basic operations (search + search) or (search + clear), where the above described sequence is used. It is a very high severity bug: the new feature "deselected allowed false " cannot be used.  
Exception 
- java.lang.RuntimeException: java.lang.IllegalStateException: Unknown key: 1
- function Grid:: findByKey 

import java.util.ArrayList;
import java.util.List;

import com.vaadin.flow.component.grid.AbstractGridSingleSelectionModel;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.html.Div;
import com.vaadin.flow.router.Route;

@SuppressWarnings("serial")
@Route("TestDeselectAllowed")
public class TestDeselectAllowed extends Div {

	Grid<Item> grid;

	/** here is the test call */
	TestDeselectAllowed() {

		setupTest();

		/** fail example */
		test_deselectNotAllowed_SetSelectSet_fail();

		/** examples were is not failing */
		// test_deselectAllowed_SetSelectSet_ok();
		// test_deselectNotAllowed_SetNoSelectSet_ok();
	}

	void setupTest() {
		grid = new Grid<>();
		grid.addColumn(Item::getCode);
		grid.addColumn(Item::getDescription);
		add(grid);
	}

	void test_deselectNotAllowed_SetSelectSet_fail() {

		setDeselectAllowed(grid, false);
		
		List<Item> list = Item.createList();
		grid.setItems(list);

		grid.getSelectionModel().select(list.get(0));

		// fill after select
		grid.setItems(Item.createList());

	}

	void test_deselectAllowed_SetSelectSet_ok() {

		setDeselectAllowed(grid, true);
		List<Item> list = Item.createList();
		grid.setItems(list);

		grid.getSelectionModel().select(list.get(0));

		// fill after select
		grid.setItems(Item.createList());
	}

	void test_deselectNotAllowed_SetNoSelectSet_ok() {
		setDeselectAllowed(grid, false);
		List<Item> list = Item.createList();
		grid.setItems(list);

		// no select
		grid.setItems(Item.createList());
	}

	static void setDeselectAllowed(Grid<?> grid, boolean deselectAllowed) {
		if (grid.getSelectionModel() instanceof AbstractGridSingleSelectionModel) {
			((AbstractGridSingleSelectionModel<?>) grid.getSelectionModel())
					.setDeselectAllowed(deselectAllowed);
		}
	}

	public static class Item {

		public String getCode() {
			return code;
		}

		public String getDescription() {
			return description;
		}

		String code;
		String description;

		public Item() {
			super();
		}

		public static List<Item> createList() {
			List<Item> list = new ArrayList<>();
			for (int i = 0; i < 5; i++) {
				Item item = new Item();
				item.code = "code " + i;
				item.description = "desc " + i;
				list.add(item);
			}

			return list;
		}
	}

}

### PR DESCRIPTION
**Pull request by hongduc-phan**
Add more new condition `selectedKeys[oldVal.key]` in `if (!grid.$connector.deselectAllowed && oldVal && selectedKeys[oldVal.key])`. The condition "cares" about when grid.activeItem = oldVal.

Fixes #850

### CODE REVIEW

File: vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridSingleSelectionIT.java [hunk 1]
```diff
@@ -85,4 +85,25 @@ public void checkDeselectionDisallowedInitially() {
         Assert.assertTrue("Row 1 was still selected after de-selecting it.",
                 !grid.getRow(1).isSelected());
     }
+
+    @Test
+    public void gridSetItemsAndSelectItemAndSetItemAfterSetDeselectAllowedFalse() {
+        open();
+
+        // De-selection is allowed(deselectAllowed is false) and then setting items for grid
```
Comment (tomivirkki) [inline vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridSingleSelectionIT.java]: Grid de-selection is not allowed at first (it's disallowed initially at `setDeselectAllowedAndSetItems`)

File: vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridSingleSelectionIT.java [hunk 2]
```diff
@@ -85,4 +85,25 @@ public void checkDeselectionDisallowedInitially() {
...
+        GridElement grid = $(GridElement.class)
+                .id(GridSingleSelectionPage.ITEMS_GRID);
+
+        // Set Items again by clicking the button
+        $("button").id(GridSingleSelectionPage.SET_ITEMS)
```
Comment (tomivirkki) [inline vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridSingleSelectionIT.java]: The button seems to do a lot more than just setting the items = it also calls `removeAllColumns`, `addColumn`, `setHeightByRows`, `setId` and also re-adds the whole grid (so it ends up being located after the button)

File: vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractGridSingleSelectionModel.java [hunk 3]
```diff
@@ -83,6 +92,11 @@ public void select(T item) {
         }
     }
 
+    private void implementSelect(T item) {
```
Comment (tomivirkki) [inline vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractGridSingleSelectionModel.java]: `implementSelect` doesn't sound right

File: vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractGridSingleSelectionModel.java [hunk 4]
```diff
@@ -72,9 +72,18 @@ public void select(T item) {
             return;
         }
         T oldItem = selectedItem;
-        doSelect(item, false);
 
-        getGrid().doClientSideSelection(Collections.singleton(item));
+        // Check if it is in case setItems
```
Comment (tomivirkki) [inline vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractGridSingleSelectionModel.java]: This just mentions one use-case which causes an issue but it's doesn't say anything about why the following code is needed in case `setItems` is used...

File: vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridSingleSelectionIT.java (hunk 1 above)
Comment (hongduc-phan) [reply vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridSingleSelectionIT.java]: correct cmt

File: vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridSingleSelectionIT.java (hunk 2 above)
Comment (hongduc-phan) [reply vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridSingleSelectionIT.java]: separated the method

File: vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractGridSingleSelectionModel.java (hunk 3 above)
Comment (hongduc-phan) [reply vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractGridSingleSelectionModel.java]: removed the method.

File: vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractGridSingleSelectionModel.java (hunk 4 above)
Comment (hongduc-phan) [reply vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractGridSingleSelectionModel.java]: changed to fix the bug in gridConnector.js

File: vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridSingleSelectionIT.java [hunk 5]
```diff
@@ -85,4 +85,25 @@ public void checkDeselectionDisallowedInitially() {
         Assert.assertTrue("Row 1 was still selected after de-selecting it.",
                 !grid.getRow(1).isSelected());
     }
+
+    @Test
+    public void gridSetItemsAndSelectItemAndSetItemAfterSetDeselectAllowedFalse() {
```
Comment (tomivirkki) [inline vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridSingleSelectionIT.java]: This test case doesn't seem to be valid. The build passes fine without the changes to the connector.

File: vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js [hunk 6]
```diff
@@ -165,20 +165,23 @@
...
-          }
-          const isSelectedItemDifferentOrNull = !grid.activeItem || !item || item.key != grid.activeItem.key;
-          if (!userOriginated && selectionMode === 'SINGLE' && isSelectedItemDifferentOrNull) {
-            grid.activeItem = item;
-            grid.$connector.activeItem = item;
-          }
-        });
+            const isSelectedItemDifferentOrNull = !grid.activeItem || !item || item.key != grid.activeItem.key;
+            if (!userOriginated && selectionMode === 'SINGLE' && isSelectedItemDifferentOrNull) {
+              grid.activeItem = item;
```
Comment (tomivirkki) [inline vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js]: Now that this isn't run for `null` value, `grid.activeItem` has an invalid value after deselection. It should be `null` but it still has an object reference. The fix should probably be done in `__activeItemChanged`

File: vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridSingleSelectionIT.java (hunk 5 above)
Comment (hongduc-phan) [reply vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridSingleSelectionIT.java]: after discussed, I corrected the test and it covers the bug

File: vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js (hunk 6 above)
Comment (hongduc-phan) [reply vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js]: have a new commit to fix the bug in __activeItemChanged.
Explain the fix: after investigating the bug, the bug comes from when setItems after select(items), the key of select items still there, and original code from master, switch the oldVal and newVal in if (!grid.$connector.deselectAllowed && oldVal) { ..... } , the condition is triggered for setItems, in observer __activeItemChanged. With this switch, it will go else if (!selectedKeys[newVal.key]) { grid.$connector.doSelection([newVal], true); } => key is unknown => bug.
My idea is if the case is raised , I call doDeselection with item is null and it will do nothing in doDeselection method.

Comment (tomivirkki) [reply vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js]: Why would you want to call `doDeselection` with `[null]`if it does nothing??? The result is the same as removing the line altogether.

Also, now that you removed `grid.activeItem = oldVal;`, active item gets set to `null` while there still is a selected item (`activeItem` and `selectedItems` are no longer in sync).

**Comment by hongduc-phan** [comment]
My fix has some issue, it does not cover all cases of the bug. So I continue to implement it and close the PR.

File: vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js (hunk 6 above)
Comment (hongduc-phan) [reply vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js]: new fix. PTAL it.

File: vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js [hunk 7]
```diff
@@ -170,14 +172,17 @@
             selectedKeys[item.key] = item;
             if (userOriginated) {
               item.selected = true;
-              grid.$server.select(item.key);
+              if (isNotSwitchNewAndOldValue) {
```
Comment (tomivirkki) [inline vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js]: This logic doesn't work! This flag is set to `false` when deselection is disabled and the user tries to deselect. The following selection of another item would not get communicated to the server because of the global falsy flag. Add a test for this case.

Rather fix this by allowing `activeItem` to be set `null` programmatically (by `doDeselection`).

Comment (hongduc-phan) [reply vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js]: as discussion in person, I pushed the new fix with adding more test that covers the case: a selection of another item would get communicated to the server.

File: vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js [hunk 8]
```diff
@@ -194,7 +194,7 @@ import { ItemCache } from '@vaadin/vaadin-grid/src/vaadin-grid-data-provider-mix
           return;
         }
         if (!newVal) {
-          if (!grid.$connector.deselectAllowed && oldVal) {
+          if (!grid.$connector.deselectAllowed && oldVal && selectedKeys[oldVal.key]) {
```
Comment (tomivirkki) [inline vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js]: The logic flow could use some cleanup:
```
if (a && b && c) {
  foo();
} else if (b && c) {
  bar();
}
```
->

```
if (b && c) {
  if (a) {
    foo();
  } else {
    bar();
  }
}
```

Comment (hongduc-phan) [reply vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js]: done.
